### ISSUE TITLE
stacker & stacker_blueprints troposphere requirements out of sync

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#188]
Right now, the required version of troposphere is different for stacker & stacker_blueprints:

```
stacker: troposphere>=1.22
stacker_blueprints: troposphere==1.7.0
```

The >= just caused issues with tests due to circleCI seemingly caching the image between runs, and it being stuck on 1.5.0, when PR #185 needed a feature from 1.6.0.

Not sure what the right thing to do here is.  We could make them match and try to keep that in sync, though not sure that's the best way.

@mhahn any comments - you said you ran into issues with this.

**Comment by phobologic** [comment]
For now I think we just need to update troposphere for stacker to match the version that it needs - ie: 1.6 in #185.  Still not sure what the right thing is to do with both stacker & stacker_blueprints depending on it.

**Comment by mhahn** [comment]
It seems reasonable to me to require that we use "compatible release" versions for both libraries since they're so connected: https://www.python.org/dev/peps/pep-0440/#compatible-release.

I was bit by just doing a blanket `troposphere>=1.2` and then there was a backwards incompatible change somewhere in there.

I think doing `troposphere~=1.7.0` in both libraries is the safest thing.

**Comment by mhahn** [comment]
https://github.com/remind101/stacker/pull/201
