### ISSUE TITLE
Support Change Sets for stack upgrades

### ISSUE THREAD

**Issue by danielkza** [remind101/stacker#195]
[Change Sets](https://aws.amazon.com/blogs/aws/new-change-sets-for-aws-cloudformation/) are a very useful AWS feature to evaluate modifications before a stack upgrade, and would fit quite well with most stacker workflows.

It would be nice if they were supported. They could be integrated into the `build` command, by creating change sets instead of directly applying changes, or into the diff command, by showing the change set description instead of just the template modifications.

(I plan to work on this on the near future, if nobody already does or plans to)

**Comment by phobologic** [comment]
Hey @danielkza - change set support was just added, though it's not in a release yet (I hope to have a release ready soon, in the next week most likely):  https://github.com/remind101/stacker/pull/178

**Comment by danielkza** [comment]
I was using the latest version from pip and missed the PR. Really great to know, I'll test it out ASAP. Sorry for the bogus report!

**Comment by phobologic** [comment]
No worries!  This release is long overdue, but we had a bunch of cool stuff coming in, so I've been holding off :)  If you have any comments/concerns/suggestions for the way it's implemented, please let us know.

One thing to keep in mind is that it's hard to implement a `diff` command in changesets when you're dealing with multiple stacks, which is why @mhahn opted for the 'interactive build' model.  Basically because if Stack B is pulling an output from Stack A, you can't know that STack B has changed till you see what happens with Stack A (at least not in anyway that I can imagine).

Anyway, thanks for giving it a try!  Let us know how it goes :)

**Comment by danielkza** [comment]
I just figured out why I thought I was up-to-date but was not: I first installed stacker by simply having `stacker` in `requirements.txt`, then tried upgrading to a local copy using `pip install -e`. It didn't work as expected because the version number didn't change, causing pip to not actually link the `stacker` script to the new copy.

I believe always bumping the version in `master` right after a release would solve it. For example, if the current `master` is released as `0.7.0`, then right afterwards the version should be bumped to `0.7.1.dev1` or something like that, according to [PEP440](https://www.python.org/dev/peps/pep-0440/#pre-releases).
