### ISSUE TITLE
Add option to specify namespace for S3 bucket

### ISSUE THREAD

**Issue by dgarbus** [remind101/stacker#347]
Hey guys,

This issue is more of a nice-to-have, but we have a relatively large number of namespaces and have chosen to use a single `stacker_bucket` for storing stack templates. The problem we are facing is that stacker writes the templates to the root of the chosen bucket, rather than using any kind of namespace. This makes it difficult to identify the exact template we are looking for without actually downloading/inspecting it.

It looks like this is where the object path is set:
https://github.com/remind101/stacker/blob/master/stacker/actions/base.py#L36

It would be great for organization if we could use `$namespace` or some sort of prefix option to group the templates into their respective folders within the bucket.

**Comment by phobologic** [comment]
There's been talk recently about changing the way we store the templates so that it no longer goes into the root of the `stacker_bucket` but instead goes to a sub path based on the name of the resulting stack.  So something like a stack named `vpc` in a namespace of `my-namespace` with a bucket of `my-bucket` would end up in:

`s3://my-bucket/my-namespace-vpc/`

Would that solve your issue?

**Comment by dgarbus** [comment]
Yep, that should be perfect. Thanks for the quick follow-up!

**Comment by phobologic** [comment]
Cool - I'll leave this issue open to track it.  Thanks for the suggestion!

**Comment by phobologic** [comment]
Hey @dgarbus (and @mchristen, since you :+1:'d the idea), I know it's been a while, but I've taken a crack at implementing this here:

https://github.com/remind101/stacker/pull/478

Let me know what you think.

**Comment by dgarbus** [comment]
Looks good to me! Thanks 👍

**Comment by phobologic** [comment]
Thanks!
