### ISSUE TITLE
Full yml for environment file

### ISSUE THREAD

**Issue by aarcro** [remind101/stacker#380]
I don't see a way to hold a list of say CIDR netblocks in my environment file, which would be really handy.

With full yml in the environment file you could easily set any value in your config, right?

**Comment by phobologic** [comment]
A long time back the environment file actually was full YAML, and it was a nightmare.  Interpreting YAML twice resulted in some strange edge cases for things like booleans (and others, can't remember exactly).  We made the choice to keep the environment file simple key/value pairs.

That said, you can hold a list of CIDR netblocks due to the fact that YAML has a compact format - for a list it's:

`[value1, value2, value3, value4]`

Let me know if that doesn't work for you!

**Comment by aarcro** [comment]
Ok, I'll try that. Didn't know how the interpretation would happen. So the string from the Environment file will get text sub'd in before the YML config is parsed as YML? Suppose that makes sense.

**Comment by phobologic** [comment]
@aarcro yep, that's exactly it.  Consider the config a template, and the environment the variables that will be substituted in, and once that's done the newly rendered template is marshalled as yaml.
