### ISSUE TITLE
Documentation xref vs rxref

### ISSUE THREAD

**Issue by aarcro** [remind101/stacker#391]
Maybe this is just a documentation issue. I can't figure out what the difference is between `xref` and `rxref` lookups. Even the implementation looks exactly the same.

**Comment by phobologic** [comment]
Hey @aarcro - it's a little confusing, I agree.  The way it works is this - assume a namespace of `my-example` and a stack being looked up of `vpc`:

output: Requires that the stack you're looking to get an output from is in your stack config, and allows you to use the relative name.  IE: As long as vpc is in your current stack config, output will automatically look for `my-example-vpc`.

xref: Doesn't require that the stack you're looking at be in your stack config, and requires a fully qualified stack name.  So rather than just being able to lookup `vpc`, you'd have to specify `my-example-vpc` in the lookup.

rxref: Provides a sort of blend of the two. It automatically combines the namespace & stack name, but doesn't require that the resulting stack be in your current stack config.  So you can still specify `vpc`, and as long as your namespace is defined as `my-example` it will still find the vpc stack, even though it's not in the stack config.

One thing to keep in mind is that only the `output` lookup can do the automatic dependency detection, since the other two have no concept of whether or not changes are pending for the stack you are looking at.

Does that make sense?

**Comment by aarcro** [comment]
I think I got it now. so rxref does the same name conversion that output does, but doesn't validate. So you could run the same env file, against two different YML files?

For my Use Case I tried xref and it worked. one env/yml for building a "non prod" environment VPC mostly. And then two different dev1.env dev2.env with the same app.yml to deploy two copies of the app in that VPC, pulled some things in with the full nonprod-vpc name.

**Comment by phobologic** [comment]
Yeah, that's it.  Basically xref & rxref behave exactly the same, only one (rxref) automatically appends the namespace to the stack name for you.

This is useful if, say, you want to break up a big config - but use the same namespace still across all the configs, so there's no reason to repeat the namespace for every output lookup, which you'd have to do if you used xref instead of rxref. It's mostly just a convenience thing.

**Comment by GarisonLotus** [comment]
@aarcro -  I just updated the stacker documentation for lookups to (hopefully) clarify xref vs rxref. This is in PR #423.  Does the change I commited make sense to you to address your confusion?

You were 100% right - the rxref documentation was a real mess.  Looks like we had just copy/pasted most of the rxref section from xref. Thanks for bringing it to our attention.

**Comment by aarcro** [comment]
Thanks! that's much more clear. Explaining the usecase of multiple .yml files being run in the same namespace really helps it click.
