### ISSUE TITLE
Support for Native CloudFormation Templates

### ISSUE THREAD

**Issue by sathed** [remind101/stacker#444]
We tried Stacker and the idea is great and well executed. The problem is that we have a bunch of stacks already written in Troposphere that output JSON/YAML CF templates. What would be the possibility of adding native support for these? It wouldn't be difficult to import the Stacker package(s) into the Troposphere templates and call something like 

```
stacker.create_blueprint(template.to_json())
```

Or something similar. You could even wrap the Troposphere template in a class and call that class from Stacker.

**Comment by phobologic** [comment]
Hey @sathed - we've talked about this in the past, and it doesn't seem (on the surface) like it would be too difficult for the base case - ie: build/destroy.  Where it *might* get tricky is with things like diff/dump, but maybe not.  It hasn't been a top priority for the maintainers since we're pretty happy with the blueprints as they are - and there's thoughts that you could actually just create a blueprint itself that could do most of what you want.

I'm actually surprised that I couldn't find a feature request for this already open - I swear we had one in the past, so maybe my search-fu just isn't working.  In the meantime, I'll leave this request open, just in case someone wants to take a stab at it!  Thanks for the request!
