### ISSUE TITLE
Changing the name of an output doesn't update the stack

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#53]
If I change the name of an output, it won't get updated until I change something else with the template.

Is this an issue with CloudFormation?

ie.

if I change an output from "EmpireControllerSG" to "EmpireControllerSecurityGroup" (because being explicit is always better ;)) and run build, stacker will skip updating that stack because it says nothing has changed and then the renamed variable won't be accessible.

**Comment by phobologic** [comment]
It appears that changing outputs or parameters doesn't matter. For example, in testing the local parameters stuff, I've removed AZCount from the Parameter list in the template.  It produces an entirely new template, but since AZCount isn't used inside the template itself, CLoudformation considers the stack to have not changed and ignores the update.  I guess all that matters are things that affect the body of the template.

**Comment by phobologic** [comment]
I'm wondering if using a dummy resource in every blueprint automatically would be a good way of handling this? It seems like that'd be 'magical' and might scare the crap out of people.  Also we'd have to find a way to deal with something like that in `diff` and `build` to stop it from showing the magic resource as a 'change'.  Any ideas on this?

**Comment by phobologic** [comment]
Honestly, I can't think of a good way to fix this - it's more a bug/feature of Cloudformation, and I think any attempts we make to get around it are just going to cause other issues.  I'm going to close this.  Feel free to re-open if you have any ideas on how we can fix it.
